version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    user: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: pg_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 60
  web:
    build: .
    container_name: my_eco_web
    command: python manage.py runserver 0.0.0.0:8005
    ports:
      - "8005:8005"
    depends_on:
      - db
  migrate:
    build: .
    command: python manage.py migrate
    volumes:
      - ./:/data/usr/src/app
    depends_on:
      db:
        condition: service_healthy